title: Jon Woolfrey
description: Under construction.
theme: minima

# Sidebar navigation links
sidebar:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"

# Other configurations
markdown: kramdown
permalink: pretty
