title: Jon Woolfrey
description: "PhD <br> Lean Six Sigma Black Belt <br> BE Mechatronics (Hons.) <br> Cert. IV Mechanical Trades"
theme: minima
url: "https://woolfrey.github.io"
collections:
  pages:
    output: true
    permalink: /:name/
    
sidebar_info:
  email:    "jonathan.woolfrey@gmail.com"
  linkedin: "https://www.linkedin.com/in/jonathanwoolfrey/"
  github:   "https://github.com/woolfrey/"
  
sidebar:
  - title: "Home"
    url: "/"
    active: true
  - title: "About Me"
    url: "/about/"
  - title: "Curriculum Vitae"
    url: "/cv/"
  - title: "Projects"
    url: "/projects/"
  - title: "Publications"
    url: "/publications/"
  - title: "Recommended Reading"
    url: "/reading/"
  - title: "Recommended Viewing"
    url: "/viewing/"
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter_opts:
    disable : true
permalink: pretty

exclude:
  - venv/
  - python/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
