title: Jon Woolfrey
description: Under construction.
theme: minima

# Additional sidebar info
sidebar_info:
  titles:
  - "Robotics Engineer 🤖"
  - "Lean Six Sigma Black Belt 🥋"
  email:    "jonathan.woolfrey@gmail.com"
  linkedin: "https://www.linkedin.com/in/jonathanwoolfrey/"
  github:   "https://github.com/woolfrey/"

# Sidebar navigation links
sidebar:
  - title: "Home"
    url: "/"
  - title: "About Me"
    url: "/about/"
  - title: "Curriculum Vitae"
    url: "/cv/"
  - title: "Publications"
    url: "/publications/"
  - title: "Recommended Reading"
    url: "/reading/"

# Specify kramdown as the Markdown processor
markdown: kramdown

# Other configurations
permalink: pretty
